# Generated by Django 5.2.7 on 2025-10-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_worker_created_by_alter_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
