# Generated by Django 5.2.7 on 2025-10-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_worker_deleted_at_worker_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='hired_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
