# Generated by Django 5.2.7 on 2025-10-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_worker_hired_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['hired_date'], 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
